### ISSUE TITLE
Some people are unable to log in to the app

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#101] opened 2016-02-17 14:03 UTC
So far I learned that Ignacio and Michał K are unable to log in to the app. After clicking the Google login button... nothing happens. Any way we could look into this? @Tade0 @theanxy @karolsojko Thanks!

**Comment by theanxy** [comment] 2016-02-18 12:15
Awaiting @mkawalec to provide more information

**Comment by theanxy** [comment] 2016-02-19 12:09
According to @mkawalec, he couldn't reproduce that anymore. Must have been fixed by #102. Let's reopen if the problem persists.

**Closed by theanxy** 2016-02-19 12:09 UTC
Labels: bug, high priority
