### ISSUE TITLE
[QA] Firebase warnings when posting comment replies

### ISSUE THREAD

**Issue by theanxy** [x-team/unleash#106] opened 2016-02-22 15:18 UTC
To investigate

![screen shot 2016-02-22 at 16 17 57](https://cloud.githubusercontent.com/assets/92843/13222345/e2f2991e-d97f-11e5-8ff3-58c74af6ff41.png)

**Comment by Tade0** [comment] 2016-02-23 19:27
I think I know why this is happening(chiefly because I introduced the changes that cause this issue). I'll take care of this.

**Comment by jkbdbrnwsk** [comment] 2016-04-06 10:40
Hey @Tade0, how is the progress on this? :)

**Comment by Tade0** [comment] 2016-04-06 22:42
To be honest I'm having trouble reproducing this one now.

Also, I just noticed that these paths seem to be off. The first one should be `/users/<user_id>/newComments/<comment_id>` and the second one `/users/<user_id>/cards/<card_id>/unread`.

@theanxy could you confirm this?

http://qa.unleash.x-team.com/ is down now, but neither `master` branch nor `qa` branch show this behaviour.

**Comment by theanxy** [comment] 2016-04-06 22:57
I can’t reproduce that firebase console error on `staging` anymore either.

As for the path – you’re right, `/newComments/` should be stashed inside user’s object instead of in the root object. Because of that, it looks like the unread comments badge hasn’t been working for some time now (another reason to have e2e tests). I’ve verified that using 2 separate unleash accounts. Fixing the path should fix the problem, but let’s keep an eye open for that problem with permissions

**Comment by Tade0** [comment] 2016-04-13 12:53
I checked and the permissions on staging should not produce such warnings. Production would probably require an update though.

**Comment by karolsojko** [comment] 2016-05-23 10:28
Closing since we don't user Firebase anymore

**Closed by karolsojko** 2016-05-23 10:28 UTC
Labels: in progress, question
