### ISSUE TITLE
Editing cards placed on a Path

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#192] opened 2016-06-28 12:45 UTC
Please add an ability to edit cards that have been already placed on a Path.

**Comment by karolsojko** [comment] 2016-06-28 13:06
duplicate of https://github.com/x-team/unleash/issues/135 ;) ?

**Comment by jkbdbrnwsk** [comment] 2016-06-28 13:07
Lol, forgot I created a ticket for this... 3 months ago. ;) Would appreciate implementing such option at your earliest convenience. ;)

**Comment by karolsojko** [comment] 2016-07-08 10:09
Will close this one and continue in #135

**Closed** 2016-07-08 10:09 UTC
Labels: enhancement
